JACK_FILE_EXT = ".jack"
TOKENIZER_FILE_EXT = "T.xml"
PARSER_FILE_EXT = ".xml"
DOUBLE_QUOTE = '"'
XML_LINE_TAB = "  "
VM_FILE_EXT = ".vm"

IF_LABEL_BEGIN = "IF_BEGIN"
ELSE_LABEL_BEGIN = "ELSE_BEGIN"
IF_ELSE_LABEL_END = "IF_ELSE_END"

WHILE_LABEL_BEGIN = "WHILE_BEGIN"
WHILE_LABEL_END = "WHILE_END"
